### ISSUE TITLE
CC0-1.0 license for code?

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/book-of-examples#12]
I really like the [CC0-1.0 license we currently use for the Roc examples repo](https://github.com/roc-lang/examples/blob/main/LICENSE). It's a license with minimal restrictions. It allows users to just copy-paste an example into their codebase (even commercial) without needing to learn about attributions.

The current license for this project (CC-BY-NC-ND-4.0) requires users to include an attribution, prohibits commercial use, and does not allow code with any modifications to be included in for example a Roc package.

The CC-BY-NC-ND-4.0 license feels like a net negative to me. I think the CC0-1.0 license would make the book more beneficial to society and lead to a better user experience without making any real sacrifices.

It seems so strange to show high quality examples but not allow people to just copy-paste them into their own projects.

Opinions welcome :)

**Comment by gvwilson** [comment]
The code is covered by the MIT License, and can be copied, remixed, included in commercial projects, etc. The CC-BY-NC-ND is for the prose (i.e., the lessons we're going to write to explain the code); I'd like to keep that in place until we have a signed contract with a publisher so that (for example) nobody can take the words we write and put them in an epub on Amazon without our permission.

**Comment by Anton-4** [comment]
Great, MIT is a lot better :)
I do still prefer CC0-1.0, I will probably open a new issue for CC0 vs MIT and close this one to prevent people from needing to read through my wrong assumptions :smile:
