### ISSUE TITLE
governance proposal: adopt Martha's Rules for decision making

### ISSUE THREAD

**Issue by gvwilson** [roc-lang/book-of-examples#9]
See [this blog post](https://third-bit.com/files/2020/08/marthas/) for a description of Martha's Rules (a lightweight mostly-consensus decision-making process for collaborative projects).

**Comment by HajagosNorbert** [comment]
Reading through it, this method seems good. I like the simplicity of it. 
Where would the list containing the decisions be stored? For me, a DECISIONS.md inside this repo seems sufficient, or a wiki page (Github has those as well), so that everything would be in one place. Do you have any suggestion?

**Comment by Anton-4** [comment]
I would prefer a meeting-free version of Martha's rules. I believe text based discussion lowers the barrier for anyone to speak up, spend some time thinking, do some research... .

I also think it helps distance the idea from the presenter. For example, if Richard were to present a proposal in a meeting it would have a higher chance of passing compared to someone else because he is an experienced speaker and has a high "authority score". I believe this effect is reduced when debating over text. I also believe it's easier to provide straight criticism this way compared to in person.

For these reasons, I expect a meeting-free approach will lead to better decisions.

**Comment by gvwilson** [comment]
1. @HajagosNorbert Agreed, decisions would go into a Markdown file in the root of the repo. In the past I've used `GOVERNANCE.md` to hold both the rules (at the top) and the decision log, but I agree a separate `DECISION.md` might be clearer.
2. @Anton-4 I agree that real-time discussion can disadvantage some people (less extroverted, not as fluent in the language being used, poor internet connection, etc.). However, one strength of Martha's Rules is that it caps discussion: in my experience, if debate is done online, it can go on for a very long time. What mechanism would you put in place to cap it so that decisions are actually made?

**Comment by Anton-4** [comment]
> What mechanism would you put in place to cap it so that decisions are actually made?

A time limit until vote could be used here as well, perhaps 24 hours?
